- name: Inject Secret Salt
        shell: bash
        run: |
          sed -i "s/REPLACE_ME_SECRET_SALT/${{ secrets.PROXY_SECRET_SALT }}/g" proxy/hwid_auth.py

      # ШАГ OBFUSCATE УДАЛЕН ДЛЯ ТЕСТА

      - name: Build with PyInstaller
        shell: cmd
        run: |
          pyinstaller packaging/windows.spec
